package com.casecode.mobilemovieexplorer.domain.model.demodetails;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Record representing detailed information about a demo movie.
 *
 * @param adult               Indicates whether the movie is for adults.
 * @param backdropPath        The backdrop path for the movie.
 * @param belongsToCollection The collection to which the movie belongs.
 * @param budget              The budget of the movie.
 * @param genres              The genres associated with the movie.
 * @param homepage            The homepage of the movie.
 * @param id                  The ID of the movie.
 * @param imdbId              The IMDb ID of the movie.
 * @param originalLanguage    The original language of the movie.
 * @param originalTitle       The original title of the movie.
 * @param overview            An overview or summary of the movie.
 * @param popularity          The popularity score of the movie.
 * @param posterPath          The poster path for the movie.
 * @param productionCompanies The production companies involved in the movie.
 * @param productionCountries The production countries of the movie.
 * @param releaseDate         The release date of the movie.
 * @param revenue             The revenue generated by the movie.
 * @param runtime             The runtime duration of the movie.
 * @param spokenLanguages     The spoken languages in the movie.
 * @param status              The status of the movie.
 * @param tagline             The tagline of the movie.
 * @param title               The title of the movie.
 * @param video               Indicates whether the movie has video content.
 * @param voteAverage         The average vote score for the movie.
 * @param voteCount           The count of votes for the movie.
 */
public record DemoDetailsResponse(
        boolean adult,
        @SerializedName("backdrop_path") String backdropPath,
        @SerializedName("belongs_to_collection") BelongsToCollection belongsToCollection,
        int budget,
        List<Genre> genres,
        String homepage,
        int id,
        @SerializedName("imdb_id") String imdbId,
        @SerializedName("original_language") String originalLanguage,
        @SerializedName("original_title") String originalTitle,
        String overview,
        double popularity,
        @SerializedName("poster_path") String posterPath,
        @SerializedName("production_companies") List<ProductionCompany> productionCompanies,
        @SerializedName("production_countries") List<ProductionCountry> productionCountries,
        @SerializedName("release_date") String releaseDate,
        int revenue,
        int runtime,
        @SerializedName("spoken_languages") List<SpokenLanguage> spokenLanguages,
        String status,
        String tagline,
        String title,
        boolean video,
        @SerializedName("vote_average") double voteAverage,
        @SerializedName("vote_count") int voteCount
) {
}